openapi: 3.0.3

info:
  title: Dispatcher API
  description: 自転車割り当てサービスのAPI定義書
  version: 1.0.0

servers:
  - url: http://127.0.0.1:5000
    description: local development server
  - url: 'https://bikeying.com'
    description: main production server

paths:
  /dispatch:
    post:
      summary: ストックされたリクエストから最適な自転車を割り当てる
      tags:
        - dispatch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DispatchBikeSchema'
      responses:
        '201':
          description: A JSON representation of the assigned bike
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDispatchedBikeSchema'
        '400':
          description: Invaild Input

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string

    LocationSchema:
      additionalProperties: false
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          description: latitude
          minimum: -90
          maximum: 90
        longitude:
          type: number
          description: longitude
          minimum: -180
          maximum: 180

    DispatchBikeSchema:
      type: object
      properties:
        df_requests:
          type: array
          items:
            type: object
            properties:
              tpep_pickup_datetime:
                type: string
                format: date-time
                description: リクエストの受付日時
              tpep_dropoff_datetime:
                type: string
                format: date-time
                description: リクエストの返却日時
              PULocation:
                $ref: '#/components/schemas/LocationSchema'
              DOLocation:
                $ref: '#/components/schemas/LocationSchema'
            required:
              - tpep_pickup_datetime
              - tpep_dropoff_datetime
              - PULocation
              - DOLocation
      required:
        - df_requests

    DispatchedBikeSchema:
      type: object
      properties:
        bike_id:
          type: string
          description: Assigned bikd ID
        user_queue_index:
          type: string
          description: リクエストID
      required:
        - bike_id
        - user_queue_index

    GetDispatchedBikeSchema:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/DispatchedBikeSchema'
      required:
        - results